<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="UTF-8">
        <title>Google Drive Example App</title>
    </head>
    <body>
        <form method="post" action="">
            <input type="text" placeholder="url" name="url"><br />
            <input type="text" placeholder="title" name="title"><br />
            <input type="text" placeholder="split size in mb" name="split"><br />
       
            <input type="submit" value="upload to google drive" name="submit"><br />
        </form>
    </body>
</html>
